export interface User {
  _id: string; //id auto generated by mongo
  email: string;
  role: 'admin' | 'responsable_region' | 'user'; // enum
  isVerified: boolean;
  isActive: boolean;
  createdAt?: string; // timestamps
  updatedAt?: string;
}

// login response
export interface LoginResponse {
  email: string;
  token: string;
}
//otp response
export interface OtpResponse {
  message: string;
  token: string;
  role: 'admin' | 'responsable_region' | 'user';
  email: string;
}
//toast
export interface Toast {
  id: number;
  message: string;
  type: 'success' | 'error' | 'info'; // Types autorisés
}
//props for user model create
export interface Props {
    isOpen: boolean;
    onClose: () => void;
    onUserCreated: () => void; 
}
//props for user model update
export interface PropsUpdate {
    isOpen: boolean;
    onClose: () => void;
    onUserUpdated: () => void; 
    user: User;
}