import type { Role } from "../utils/permissions";

export interface User {
  _id: string; //id auto generated by mongo
  email: string;
  role: 'administrateur' | 'responsable region' | 'utilisateur'; // enum
  token: string;
  isVerified: boolean;
  isActive: boolean;
  createdAt?: string; // timestamps
  updatedAt?: string;
}
//props for auth context
export interface AuthContextType {
  user: any
  loginUser: (userData: any) => void
  logout: () => void
  isLoading: boolean;
}
// login response
export interface LoginResponse {
  email: string;
  token: string;
}
//otp response
export interface OtpResponse {
  message: string;
  token: string;
  role: 'administrateur' | 'responsable region' | 'utilisateur';
  email: string;
}
//toast
export interface Toast {
  id: number;
  message: string;
  type: 'success' | 'error' | 'info'; // Types autorisés
}
export interface ToastContextType {
  addToast: (message: string, type?: 'success' | 'error') => void;
}
//props for user model create
export interface Props {
    isOpen: boolean;
    onClose: () => void;
    onUserCreated: () => void; 
}
//props for dashboard
export interface PropsDashboard {
  role: Role;
  permission: string;
  children: React.ReactNode;
}
//props for user model update
export interface PropsUpdate {
    isOpen: boolean;
    onClose: () => void;
    onUserUpdated: () => void; 
    user: User;
}