import type { Role } from "../utils/permissions";
  
export interface User {
  _id: string; //id auto generated by mongo
  email: string;
  role: 'administrateur' | 'responsable region' | 'utilisateur' | 'Gestionnaire de Stock'; // enum
  region?: string;
  token: string;
  isVerified: boolean;
  isActive: boolean;
  createdAt?: string; // timestamps
  updatedAt?: string;
}
//props for auth context
export interface AuthContextType {
  user: any
  loginUser: (userData: any) => void
  logout: () => void
  isLoading: boolean;
}
// login response
export interface LoginResponse {
  email: string;
  token: string;
}
//otp response
export interface OtpResponse {
  message: string;
  token: string;
  role: 'administrateur' | 'responsable region' | 'utilisateur' | 'Gestionnaire de Stock';
  region?: string;
}
//toast
export interface Toast {
  id: number;
  message: string;
  type: 'success' | 'error' | 'info'; // Types autorisés
}
export interface ToastContextType {
  addToast: (message: string, type?: 'success' | 'error') => void;
}
//props for commande model create
export interface PropsCommande {
    isOpen: boolean;
    onClose: () => void;
    onCommandeCreated: () => void; 
}
//props for demande model create
export interface PropsDemande {
    isOpen: boolean;
    onClose: () => void;
    onDemandeCreated: () => void; 
}
//props for demande model update
export interface PropsDemandeUpdate {
    isOpen: boolean;
    onClose: () => void;
    onDemandeUpdated: () => void; 
    demande: Demande;
}
//props for user model create
export interface PropsUser {
    isOpen: boolean;
    onClose: () => void;
    onUserCreated: () => void; 
}
//props for user model update
export interface PropsUserUpdate {
    isOpen: boolean;
    onClose: () => void;
    onUserUpdated: () => void; 
    user: User;
}
//props for dashboard
export interface PropsDashboard {
  role: Role;
  permission: string;
  children: React.ReactNode;
}
//region interface
export interface RegionStock {
  _id: string;
  totalValue: number;
  totalQuantity: number;
  
}
export interface Product {
    _id: string;
    codeArticle: string;
    libelle: string;
    quantite: number;
    unite: string;
    prix: number;
}

export interface StockItem {
    _id: string;
    quantite: number;
    product_id: Product;
}
//dashboard response
export interface DashboardResponse {
  totalProducts: number;
  totalQuantity: number;
  totalInventoryValue: number;
  stockByRegion: RegionStock[];
  lowStockItems: StockItem[];
}
export interface Transaction {
    id: string;
    product: string;
    amount: number;
    status: 'success' | 'pending' | 'failed';
    date: string;
    region: string;
}

export interface TopItem {
    name: string;
    sales: number;
    revenue: number;
    growth: number;
}
export interface Demande {
    _id: string;
    user_id: User;
    status: 'EN_ATTENTE' | 'REJETEE' | 'ACCEPTEE';
    items: { quantite: number; product_id: Product }[];
    description: string;
    createdAt: string;
}
export interface ProductProps {
    isOpen: boolean;
    onClose: () => void;
    onProductCreated: () => void; 
}
export interface Commande {
    _id: string;
    demande_id: Demande;
    items: { quantite: number; product_id: Product }[];
    region: string;
    status: 'EN_PREPARATION' | 'EXPEDIEE' | 'LIVREE';
    createdAt: string;
}
export interface ProductPropsUpdate {
    isOpen: boolean;
    onClose: () => void;
    onProductUpdated: () => void; 
    product: Product;
}
export interface ConfirmModalProps {
    config: {
        title: string;
        confirmValue: string;
        onConfirm: () => void;
    };
    onClose: () => void;
}
export interface ConfirmConfig {
  title: string;
  confirmValue: string;
  onConfirm: () => void;
}

export interface ConfirmContextType {
  showConfirm: (title: string, confirmValue: string, onConfirm: () => void) => void;
}