export const Region = [
        { value: 'Tunis', label: 'Tunis' },
        { value: 'Sfax', label: 'Sfax' },
        { value: 'Sousse', label: 'Sousse' },
        { value: 'Monastir', label: 'Monastir' },
        { value: 'Nabeul', label: 'Nabeul' },
        { value: 'Beja', label: 'Beja' },
        { value: 'Bizerte', label: 'Bizerte' },
        { value: 'Gabes', label: 'Gabes' },
        { value: 'Gafsa', label: 'Gafsa' },
        { value: 'Jendouba', label: 'Jendouba' },
        { value: 'Kasserine', label: 'Kasserine' },
        { value: 'Kairouan', label: 'Kairouan' },
        { value: 'Kebili', label: 'Kebili' },
        { value: 'Ariana', label: 'Ariana' },
        { value: 'Kef', label: 'Kef' },
        { value: 'Mahdia', label: 'Mahdia' },
        { value: 'Manouba', label: 'Manouba' },
        { value: 'Medenine', label: 'Medenine' },
        { value: 'Sidi Bouzid', label: 'Sidi Bouzid' },
        { value: 'Siliana', label: 'Siliana' },
        { value: 'Tozeur', label: 'Tozeur' },
        { value: 'Zaghouan', label: 'Zaghouan' },
        { value: 'Tataouine', label: 'Tataouine' },
        { value: 'Ben Arous', label: 'Ben Arous' }
    ];